meta_product_name: "Tralha App"
meta_title: "TralhaApp- Descarte com sabedoria"
meta_description: "plataforma para facilitar a comunicação entre as pessoas e as organizações de reciclagem e reuso de materiais"
meta_image: "renezin.png"
twitter_account: "@tralha_twitter_account"   # required for Twitter Cards
