meta_product_name: "Tralha App"
meta_title: "TralhaApp - Descarte com sabedoria"
meta_description: "Plataforma para facilitar a comunicação entre as pessoas e as organizações de reciclagem e reuso de materiais"
meta_image: "renezinog.png"
twitter_account: "@tralha_twitter_account"   # required for Twitter Cards
